### ISSUE TITLE
Can't run examples on OS X

### ISSUE THREAD

**Issue by apbendi** [srh/kit#1]
So Kit does indeed compile on OS X :+1: 

However, I cannot currently compile any of the examples with any version of the compiler:

```
Bens-MacBook-Pro:examples bendi$ ../s3 helloworld.ki
Could not open file for module helloworld.ki
Failed.
Bens-MacBook-Pro:examples bendi$ ../s2 helloworld.ki
Could not open file for module helloworld.ki
Failed.
Bens-MacBook-Pro:examples bendi$ ../out helloworld.ki
Could not read file helloworld.ki.ki.
Could not read file '' for module helloworld.ki.
(Fail.)
```

**Comment by srh** [comment]
Oh so I'm going to have to make the examples actually work now, eh?

**Comment by srh** [comment]
Here's another try, still broken:

```
$ ../s3 helloworld
Trouble parsing module at helloworld.ki:3:14
Failed.
```

Changes made:
- s2 and s3 now tolerate ".ki" suffixes on the command line -- see 2fef05e56baa2531297bd969b62e053cc37d195a
- helloworld now works with current proto-Kit -- see a43731d9c24389ae26da9bfc1d432f5b7792a5ad
- helloworld is moved to its own directory and has a fancy build script.

This should work on OS X:

```
[pc8 ~/kit]$ ./osx_build_s3.sh 
Success.
Success.
[pc8 ~/kit]$ cd examples/helloworld
[pc8 ~/kit/examples/helloworld]$ ./build.sh 
Success.
[pc8 ~/kit/examples/helloworld]$ ./a.out
Hello, world!
```

**Comment by apbendi** [comment]
:ok_hand: got it working, so now am I allowed to bother you for basic info on the language ;)

**Comment by srh** [comment]
Yes.
